/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */

export type CreateUserInputRole = typeof CreateUserInputRole[keyof typeof CreateUserInputRole];


export const CreateUserInputRole = {
  owner: 'owner',
  admin: 'admin',
  technician: 'technician',
  accountant: 'accountant',
} as const;
