/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */

export interface CustomerInput {
  /** @minLength 1 */
  name: string;
  contactPerson?: string;
  phone?: string;
  mobile?: string;
  address?: string;
  email?: string;
  taxId?: string;
  source?: string;
  status?: string;
  discountScheme?: string;
  notes?: string;
  primarySalesRepId?: number;
}
