/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */

export type DashboardSummaryTodayWorkOrdersItem = {
  id?: number;
  /** @nullable */
  workOrderNumber?: string | null;
  /** @nullable */
  customerName?: string | null;
  /** @nullable */
  scheduledTime?: string | null;
  /** @nullable */
  technicians?: string | null;
  /** @nullable */
  installAddress?: string | null;
};
