/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */

export type ListMaintenanceRemindersParams = {
customerId?: number;
status?: string;
/**
 * 是否只顯示即將到期的提醒 (true/false)
 */
upcoming?: string;
};
