/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */

export interface Receivable {
  id: number;
  customerId: number;
  /** @nullable */
  customerName?: string | null;
  /** @nullable */
  workOrderId?: number | null;
  /** @nullable */
  workOrderNumber?: string | null;
  /** @nullable */
  projectName?: string | null;
  /** @nullable */
  projectType?: string | null;
  /** @nullable */
  completionDate?: string | null;
  totalAmount: number;
  receivedAmount: number;
  paymentStatus: string;
  /** @nullable */
  expectedPaymentDate?: string | null;
  /** @nullable */
  actualPaymentDate?: string | null;
  /** @nullable */
  paymentMethod?: string | null;
  /** @nullable */
  notes?: string | null;
  invoiceStatus: string;
  /** @nullable */
  invoiceType?: string | null;
  /** @nullable */
  taxId?: string | null;
  /** @nullable */
  invoiceTitle?: string | null;
  /** @nullable */
  invoiceNumber?: string | null;
  /** @nullable */
  invoiceDate?: string | null;
  /** @nullable */
  invoiceNotes?: string | null;
  createdAt: string;
  updatedAt: string;
}
