/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateProductInput {
  brand?: string;
  category?: string;
  /** @minLength 1 */
  name?: string;
  model?: string;
  spec?: string;
  unit?: string;
  imageUrl?: string;
  isActive?: boolean;
  /** @nullable */
  costPrice?: number | null;
  /** @nullable */
  retailPrice?: number | null;
  /** @nullable */
  wholesalePrice?: number | null;
  /** @nullable */
  minPrice?: number | null;
  taxIncluded?: boolean;
  stockQty?: number;
  /** @nullable */
  safetyStock?: number | null;
  warehouseLocation?: string;
  coolingCapacity?: string;
  heatingCapacity?: string;
  cspf?: string;
  energyEfficiency?: string;
  voltage?: string;
  refrigerant?: string;
  /** @nullable */
  warrantyMonths?: number | null;
  notes?: string;
}
