/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateWholesaleReceivableInput {
  receivedAmount?: number;
  dueDate?: string;
  paidDate?: string;
  paymentStatus?: string;
  paymentMethod?: string;
  notes?: string;
}
