/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */

export interface Warranty {
  id: number;
  customerId: number;
  /** @nullable */
  customerName?: string | null;
  /** @nullable */
  acUnitId?: number | null;
  startDate: string;
  endDate: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  notes?: string | null;
  createdAt: string;
}
