/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */
import type { WholesaleQuoteItem } from './wholesaleQuoteItem';

export interface WholesaleQuote {
  id: number;
  /** @nullable */
  quoteNumber?: string | null;
  /** @nullable */
  customerId?: number | null;
  /** @nullable */
  customerName?: string | null;
  quoteDate: string;
  /** @nullable */
  expiryDate?: string | null;
  /** @nullable */
  salesperson?: string | null;
  /** @nullable */
  notes?: string | null;
  subtotal: string;
  taxRate: string;
  taxAmount: string;
  shippingFee: string;
  total: string;
  status: string;
  items?: WholesaleQuoteItem[];
  createdAt: string;
  updatedAt: string;
}
