/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */

export interface WholesaleQuoteItemInput {
  /** @nullable */
  productId?: number | null;
  productName: string;
  brand?: string;
  model?: string;
  unit?: string;
  /** @minimum 1 */
  qty: number;
  unitPrice: number;
  discount?: number;
  amount?: number;
  sortOrder?: number;
}
