/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */

export interface WholesaleCustomer {
  id: number;
  companyName: string;
  /** @nullable */
  contactPerson?: string | null;
  /** @nullable */
  mobile?: string | null;
  /** @nullable */
  telephone?: string | null;
  /** @nullable */
  taxId?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  paymentTerms?: string | null;
  /** @nullable */
  creditLimit?: string | null;
  /** @nullable */
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
}
