/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */
import type { WholesaleOrderItem } from './wholesaleOrderItem';

export interface WholesaleOrder {
  id: number;
  /** @nullable */
  orderNumber?: string | null;
  /** @nullable */
  quoteId?: number | null;
  /** @nullable */
  quoteNumber?: string | null;
  /** @nullable */
  customerId?: number | null;
  /** @nullable */
  customerName?: string | null;
  orderDate: string;
  /** @nullable */
  expectedDelivery?: string | null;
  /** @nullable */
  salesperson?: string | null;
  /** @nullable */
  notes?: string | null;
  subtotal: string;
  taxRate: string;
  taxAmount: string;
  shippingFee: string;
  total: string;
  status: string;
  items?: WholesaleOrderItem[];
  createdAt: string;
  updatedAt: string;
}
