/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */

export interface WorkOrderEquipmentItem {
  id: number;
  workOrderId: number;
  /** @nullable */
  brand?: string | null;
  /** @nullable */
  model?: string | null;
  /** @nullable */
  quantity?: number | null;
  /** @nullable */
  indoorUnits?: number | null;
  /** @nullable */
  outdoorUnits?: number | null;
  /** @nullable */
  floor?: string | null;
  sortOrder: number;
}
