/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */

export interface CustomerAddressInput {
  /** @minLength 1 */
  label: string;
  /** @minLength 1 */
  address: string;
  isDefault?: boolean;
}
