/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */
import type { Customer } from './customer';
import type { DashboardSummaryTodayWorkOrdersItem } from './dashboardSummaryTodayWorkOrdersItem';

export interface DashboardSummary {
  totalCustomers: number;
  totalQuotes: number;
  totalWorkOrders: number;
  pendingWorkOrders: number;
  inProgressWorkOrders?: number;
  completedWorkOrders?: number;
  totalPaymentsAmount: number;
  upcomingMaintenanceCount: number;
  expiringWarrantiesCount: number;
  totalReceivables?: number;
  totalUnpaid?: number;
  overdueAmount?: number;
  paidThisMonthAR?: number;
  invoiceNotIssuedCount?: number;
  todayWorkOrderCount?: number;
  todayPaymentsAmount?: number;
  todayMaintenanceCount?: number;
  monthlyQuoteAmount?: number;
  monthlyWonAmount?: number;
  monthlyPaidAmount?: number;
  todayDueCount?: number;
  todayWarrantyExpiryCount?: number;
  todayReminderCount?: number;
  todayWorkOrders?: DashboardSummaryTodayWorkOrdersItem[];
  recentCustomers?: Customer[];
}
