/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */
import type { QuoteItemInput } from './quoteItemInput';

export interface QuoteUpdate {
  customerId?: number;
  customerName?: string;
  contactPerson?: string;
  title?: string;
  description?: string;
  amount?: number;
  discountAmount?: number;
  finalAmount?: number;
  status?: string;
  notes?: string;
  address?: string;
  customerPhone?: string;
  taxType?: string;
  salesRepId?: number;
  items?: QuoteItemInput[];
}
