/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */

export interface QuoteItem {
  id: number;
  quoteId: number;
  category: string;
  itemName: string;
  /** @nullable */
  brand?: string | null;
  quantity: number;
  unit: string;
  unitPrice: number;
  subtotal: number;
  /** @nullable */
  notes?: string | null;
  sortOrder: number;
}
