/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */

export interface ReceivableUpdate {
  totalAmount?: number;
  expectedPaymentDate?: string;
  actualPaymentDate?: string;
  paymentMethod?: string;
  notes?: string;
  invoiceStatus?: string;
  invoiceType?: string;
  taxId?: string;
  invoiceTitle?: string;
  invoiceNumber?: string;
  invoiceDate?: string;
  invoiceNotes?: string;
}
