/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */
import type { WholesaleQuoteItemInput } from './wholesaleQuoteItemInput';

export interface WholesaleOrderInput {
  /** @nullable */
  quoteId?: number | null;
  quoteNumber?: string;
  /** @nullable */
  customerId?: number | null;
  customerName?: string;
  orderDate: string;
  expectedDelivery?: string;
  salesperson?: string;
  notes?: string;
  taxRate?: number;
  shippingFee?: number;
  status?: string;
  items: WholesaleQuoteItemInput[];
}
