/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkOrderEquipmentItemInput } from './workOrderEquipmentItemInput';

export interface WorkOrderUpdate {
  /** @nullable */
  customerId?: number | null;
  customerName?: string;
  title?: string;
  status?: string;
  contactPerson?: string;
  mobilePhone?: string;
  telephone?: string;
  installAddress?: string;
  scheduledDate?: string;
  scheduledTime?: string;
  completedDate?: string;
  assignedTo?: string;
  assistantTo?: string;
  projectType?: string;
  acBrand?: string;
  modelNumber?: string;
  quantity?: number;
  indoorUnits?: number;
  outdoorUnits?: number;
  floorLevel?: string;
  hasElevator?: string;
  description?: string;
  notes?: string;
  technicians?: string;
  equipmentItems?: WorkOrderEquipmentItemInput[];
}
