/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * 晟風工程 ERP API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkOrderEquipmentItem } from './workOrderEquipmentItem';

export interface WorkOrder {
  id: number;
  /** @nullable */
  customerId?: number | null;
  /** @nullable */
  customerName?: string | null;
  /** @nullable */
  quoteId?: number | null;
  /** @nullable */
  workOrderNumber?: string | null;
  title: string;
  status: string;
  /** @nullable */
  contactPerson?: string | null;
  /** @nullable */
  mobilePhone?: string | null;
  /** @nullable */
  telephone?: string | null;
  /** @nullable */
  installAddress?: string | null;
  /** @nullable */
  scheduledDate?: string | null;
  /** @nullable */
  scheduledTime?: string | null;
  /** @nullable */
  completedDate?: string | null;
  /** @nullable */
  assignedTo?: string | null;
  /** @nullable */
  assistantTo?: string | null;
  /** @nullable */
  projectType?: string | null;
  /** @nullable */
  acBrand?: string | null;
  /** @nullable */
  modelNumber?: string | null;
  /** @nullable */
  quantity?: number | null;
  /** @nullable */
  indoorUnits?: number | null;
  /** @nullable */
  outdoorUnits?: number | null;
  /** @nullable */
  floorLevel?: string | null;
  /** @nullable */
  hasElevator?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  technicians?: string | null;
  equipmentItems?: WorkOrderEquipmentItem[];
  createdAt: string;
  updatedAt: string;
}
