// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pdf-preview-dialog.tsx": () => import("../components/mockups/pdf-preview-dialog.tsx")
};
